//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RULKA.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int ID { get; set; }
        public string ProductCategory1 { get; set; }
    }
}
